### ISSUE TITLE
削除でapt install 追加で apt remove は逆では?

### ISSUE THREAD

**Issue by yabuki** [l/debian-handbook#1]
https://debian-handbook.info/browse/ja-JP/stable/sect.apt-get.html
を見て気がつきましたが。

> 6.2.2. インストールと削除
> APT を使うと、システムからパッケージを追加したり削除したりできます。削除は apt install  package、追加は apt remove package のようにして行います。どちらの場合も APT は自動的に、追加するパッケージの動作に必要なパッケージをインストールし、削除対象のパッケージの削除後に不要になるパッケージを削除します。apt purge package コマンドを実行すれば完全にアンインストール、つまり設定ファイルも削除します。

これ、削除でapt install 追加で apt remove は逆では?

**Comment by l** [comment]
矢吹さま

綾小路です。ご連絡ありがとうございます。

At Wed, 1 Feb 2017 06:59:41 -0800,
YABUKI Yukiharu <notifications@github.com> wrote:
> 
> https://debian-handbook.info/browse/ja-JP/stable/sect.apt-get.html
> を見て気がつきましたが。
> 
>     6.2.2. インストールと削除
>     APT を使うと、システムからパッケージを追加したり削除したりできます。削除は
>     apt install package、追加は apt remove package のようにして行います。どち
>     らの場合も APT は自動的に、追加するパッケージの動作に必要なパッケージをイ
>     ンストールし、削除対象のパッケージの削除後に不要になるパッケージを削除しま
>     す。apt purge package コマンドを実行すれば完全にアンインストール、つまり設
>     定ファイルも削除します。
>    
> これ、削除でapt install 追加で apt remove は逆では?

逆でした。
修正を含むコミットを作業用ブランチに push しました [1]。ご確認ください。
問題があれば 1 週間以内にご連絡ください。
連絡がなければ、1 週間後に本家リポジトリに push します。

[1] https://github.com/l/debian-handbook/commit/9369c4623d8c1ff9d7527f67bbf8b98892932c67

よろしくお願いします。
綾小路龍之介
-- 
AYANOKOUZI, Ryuunosuke <i38w7i3@yahoo.co.jp>

**Comment by l** [comment]
矢吹さま

綾小路です。

At Thu, 2 Feb 2017 04:52:31 -0800,
l <notifications@github.com> wrote:
> 
> 修正を含むコミットを作業用ブランチに push しました [1]。ご確認ください。
> 問題があれば 1 週間以内にご連絡ください。
> 連絡がなければ、1 週間後に本家リポジトリに push します。
> 
> [1] https://github.com/l/debian-handbook/commit/9369c4623d8c1ff9d7527f67bbf8b98892932c67

お名前とメールアドレスを間違えていたので、修正したコミットを push しました [1]。ご確認ください。
前のコミットは作業用ブランチ [2] から消えたので、本家ブランチには push されません。

[1] https://github.com/l/debian-handbook/commit/5e5de10d2954d6a6b01bf66be8347e2cfb6e82ea
[2] https://github.com/l/debian-handbook/commits/jessie/master/translation/ja_JP/work_daily

よろしくお願いします。
綾小路龍之介
-- 
AYANOKOUZI, Ryuunosuke <i38w7i3@yahoo.co.jp>

**Comment by yabuki** [comment]
見ました。対応ありがとうございました。
webに反映されたら、本issueはcloseしてくださいませ。

**Comment by l** [comment]
矢吹さま

綾小路です。

At Thu, 2 Feb 2017 20:16:55 -0800,
YABUKI Yukiharu <notifications@github.com> wrote:
> 
> 見ました。対応ありがとうございました。
> webに反映されたら、本issueはcloseしてくださいませ。

本家の web に修正が反映されたので、close します。
ご協力ありがとうございました。

綾小路龍之介
-- 
AYANOKOUZI, Ryuunosuke <i38w7i3@yahoo.co.jp>
